### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by sheharyarn**
Cleans up the code a bit and fixes all the warnings being shown during compilation on Elixir 1.5+

### CODE REVIEW

**Comment by MikaAK** [comment]
Thanks for the PR, I've upgraded the deps and published it up to hex 😄

**Comment by sheharyarn** [comment]
~@MikaAK `Trello.generate_auth_url` is no longer available in the new package. What's the pattern of generating authorization request urls for Trello in the new release?~

Nevermind, it's `Trello.Config.generate_auth_url`.

**Comment by sheharyarn** [comment]
But now all requests are failing, mainly raised by hackney:

```
iex(6)> Trello.get_board("sLRy2SJ9", token)
** (CaseClauseError) no case clause matching: []
    (hackney) /Users/Psy/code/app/app/deps/hackney/src/hackney_url.erl:211: :hackney_url.parse_netloc/2
    (hackney) /Users/Psy/code/app/app/deps/hackney/src/hackney.erl:345: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:633: HTTPoison.Base.request/9
    (trello) lib/trello.ex:5: Trello.get/2
```

**Comment by MikaAK** [comment]
There's an http module that sets the defaults for httpoison. It's probably set a bit wrong from the upgrade. You're welcome to fix it or I may be able to layer tonight

**Pull request merged**
